[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "refrakt_core"
version = "0.3.2"
description = "Core ML/DL training library for Refrakt framework"
readme = "README.md"
authors = [
    { name = "Akshath Mangudi", email = "akshathmangudi@gmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0",
    "torchvision",
    "einops",
    "matplotlib",
    "numpy",
    "requests",
    "pillow",
    "tqdm", 
    "omegaconf", 
    "timm", 
    "pydantic", 
    "scikit-learn", 
    "xgboost"
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py310"
lint.select = ["E", "F", "B", "I"]

[project.urls]
"Homepage" = "https://github.com/refrakt-hub/refrakt_core"
"Bug Tracker" = "https://github.com/refrakt-hub/refrakt_core/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"refrakt_core.integrations.yaml" = ["*.yaml"]